FROM golang:stretch as build
WORKDIR /go/src/github.com/OWASP/Amass1
RUN apt update && apt install -y git && go get -f -u github.com/OWASP/Amass/...

# Build python worker for amass
FROM ubuntu:16.04
LABEL Name=amass_black Version=1.0.0

COPY --from=build /go/bin/amass /bin/amass

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update

RUN apt install -y \
    build-essential \
    python3.6 \
    python3.6-dev \
    python3-pip \
    vim

RUN python3.6 -m pip install --upgrade pip

WORKDIR /app
ADD . /app

RUN python3.6 -m pip install -r requirements.txt

CMD ["python3.6", "spawn_worker.py", "amass", "--config", "/app/config/config_docker.yml"]
